version: "3.8"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: chatdb
    volumes:
      - ./db_data:/var/lib/postgresql/data  # Указывает, что данные будут храниться в корневой директории в папке db_data
    ports:
      - "5432:5432"
    networks:
      - app-network

  website:
    build: ./website

    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@db:5432/chatdb"
    networks:
      - app-network

  chat:
    build: ./chat
    depends_on:
      - website
    ports:
      - "8001:8001"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - website
      - chat
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:  # Это объявляет volume для хранения данных
